var insights =
{
  'twitter'     : [
                    { name: 'TwitterFollowing',              linkType: 'twitter',                                         title: "Following",                        description: "Twitter accounts that you follow."                                                                   },
                    { name: 'TwitterFollower',               linkType: 'twitter',                                         title: "Follower",                         description: "Twitter accounts that follow you."                                                                   }
                  ],
//  'linkedin'    : [
//                    { name: 'OneLinkedInHop',                linkType: 'linkedin',   regex: '.*linkedin\.com\/(in|pub)',  title: "Your Connections",                 description: "People that you are connected to on LinkedIn."                                                       },
//                    { name: 'TwoLinkedInHops',               linkType: 'linkedin',   regex: '.*linkedin\.com\/(in|pub)',  title: "Two Hops Away",                    description: "People that are only two hops away from you on LinkedIn."                                            },
//                    { name: 'LinkedInSameLocation',          linkType: 'linkedin',   regex: '.*linkedin\.com\/(in|pub)',  title: "Same Location As Me",              description: "People that are located in the same place as you."                                                   },
//                    { name: 'CompanyHasFirstConnection',     linkType: 'linkedin',   regex: '.*linkedin\.com\/company',   title: "Companies With 1st Connections",   description: "Companies that have people you are directly connected to on LinkedIn."                               },
//                    { name: 'CompanyHasConnection',          linkType: 'linkedin',   regex: '.*linkedin\.com\/company',   title: "Companies With Connections",       description: "Companies that have people you are connected to or are connected to somebody you know on LinkedIn."  },
//                    { name: 'LinkedInSpecificPerson',        linkType: 'linkedin',   regex: '.*linkedin\.com\/(in|pub)',  title: "Specific Person Type",             description: "People who fit a specific profile according to organization title and whether they are in the same location as you.",
//                          inputFields: [ { field: 'title',             name: 'Role',                type: 'titleSearch',    title: 'any', organization: 'any', description: "Role the person has held at an organization." },
//                                         { field: 'industry',          name: 'Industry',            type: 'industrySearch', industry: 'any', description: "Industry the person is in." },
//                                         { field: 'location',          name: 'Location',            type: 'locationSearch', location: 'any', description: "Current location the person is located in." } ] }
//                  ],
//  'ultralinkme' : [
//                    { name: 'CrunchbaseFundedCompany',       linkType: 'crunchbase', regex: '.*crunchbase\.com\/organization', title: "Funded Company",                   description: "Companies that have had at least one round of funding."                                              },
//                    { name: 'CrunchbaseUnfundedCompany',     linkType: 'crunchbase', regex: '.*crunchbase\.com\/organization', title: "Unfunded Company",                 description: "Companies that have no record of taking outside funding."                                            },
//                    { name: 'CrunchbaseInvestor',            linkType: 'crunchbase', regex: '.*crunchbase\.com\/person',       title: "Individual Investor",              description: "People who have made at least one investment into a company."                                        },
//                    { name: 'CrunchbaseCompaniesInvestedBy', linkType: 'crunchbase', regex: '.*crunchbase\.com\/organization', title: "Companies Invested In By",         description: "Companies that have been invested in by a specifc person, company or financial organization.",
//                        inputFields: [ { field: 'investor',            name: '',                    type: 'investorSearch', investor: 'any', description: "Individual or company name." } ] },
//                    { name: 'CrunchbaseCompaniesAcquiredBy', linkType: 'crunchbase', regex: '.*crunchbase\.com\/organization', title: "Companies Acquired By",            description: "Companies that have been acquired by a specifc person, company or financial organization.",
//                        inputFields: [ { field: 'buyer',               name: '',                    type: 'investorSearch', investor: 'any', description: "Company name." } ] },
//                    { name: 'CrunchbaseSpecificCompany',     linkType: 'crunchbase', regex: '.*crunchbase\.com\/organization', title: "Specific Company Type",            description: "Companies that fit a specific profile according to number of employees, years in operation, number of funding rounds, number of acquisitions and whether it is publicly traded.",
//                        inputFields: [ { field: 'number_of_employees', name: 'Employees',           type: 'numericCompare', compare: '=', value: 'any', description: "Number of employees." },
//                                       { field: 'years_old',           name: 'Years Old',           type: 'numericCompare', compare: '=', value: 'any', description: "Number of years the company has existed." },
//                                       { field: 'num_funding_rounds',  name: 'Funding Rounds',      type: 'numericCompare', compare: '=', value: 'any', description: "Number of funding rounds the company has received." },
//                                       { field: 'num_acquisitions',    name: 'Acquisitions',        type: 'numericCompare', compare: '=', value: 'any', description: "Number of acquisitions the company has made." },
//                                       { field: 'is_public',           name: 'Publicly Traded',     type: 'selectBox',      options: ['any', 'yes', 'no'], value: 'any', description: "Whether the company is recorded as being publicly traded or not." } ] },
//                    { name: 'CrunchbaseSpecificPerson',      linkType: 'crunchbase', regex: '.*crunchbase\.com\/person',  title: "Specific Person Type",             description: "People who fit a specific profile according to number of investments, educational degree and organization title.",
//                        inputFields: [ { field: 'num_investments',     name: 'Investments',         type: 'numericCompare', compare: '=', value: 'any', description: "Number of investments the person has made." },
//                                       { field: 'degree_in',           name: 'Degree',              type: 'degreeSearch',   degree: 'any', study: 'any', description: "Type (BS, MS, MBA, etc...) and field (CS, Economics, Philosophy, etc...) that the person holds a degree in." },
//                                       { field: 'school',              name: 'School',              type: 'schoolSearch',   school: 'any', description: "Educational institution that the person has attended." },
//                                       { field: 'title',               name: 'Role',                type: 'titleSearch',    title: 'any', organization: 'any', description: "Role (Founder, CEO, Engineer, etc...) the person has held at an organization." } ] }
//                  ],
  'angellist'   : [
                    { name: 'OneAngelListHop',               linkType: 'angellist',                                       title: "Your Connections",                 description: "People that you are connected to on AngelList."                                                      },
                    { name: 'TwoAngelListHops',              linkType: 'angellist',                                       title: "Two Hops Away",                    description: "People that are only two hops away from you on AngelList."                                           },
                    { name: 'AngelListSameLocation',         linkType: 'angellist',                                       title: "Same Location As Me",              description: "People that are located in the same place as you."                                                   },
                    { name: 'StartupHasFirstConnection',     linkType: 'angellist',                                       title: "Companies With 1st Connections",   description: "Companies that have people you are directly connected to on AngelList."                              },
                    { name: 'StartupHasConnection',          linkType: 'angellist',                                       title: "Companies With Connections",       description: "Companies that have people you are connected to or are connected to somebody you know on AngelList." },
                    { name: 'RaisingMoneyOnAngelList',       linkType: 'angellist',                                       title: "Companies Raising Money",          description: "Companies that are currently raising money publicly on AngelList." },
                    { name: 'AngelListSpecificPerson',       linkType: 'angellist',                                       title: "Specific Person Type",             description: "People who fit a specific profile according to number of investments, organization title and whether they are in the same location as you.",
                          inputFields: [ { field: 'num_investments',   name: 'Investments',         type: 'numericCompare', compare: '=', value: 'any', description: "Number of investments the person has made." },
                                         { field: 'title',             name: 'Role',                type: 'titleSearch',    title: 'any', organization: 'any', title_options: { any: 'any', founder: 'Founder', partner: 'Partner', employee: 'Employee', investor: 'Investor', advisor: 'Advisor', board_member: 'Board Member', referrer: 'Referrer', mentor: 'Mentor', customer: 'Customer', endorser: 'Endorser' }, description: "Role the person has held at an organization." },
                                         { field: 'location',          name: 'Location',            type: 'locationSearch', location: 'any', description: "Current location the person is located in." } ] }
                  ]
};
